### PR TITLE
Updating sdx diagram

### PR DESCRIPTION
**Pull request by anwilkie**
The purpose of this pull request is to update the SDX diagram in the README.md file.

[Trello card](https://trello.com/c/b2kVJId5)

### CODE REVIEW

**Review by AndrewTorrance — DISMISSED** [review]
I am not sure about the symbols used , I dont know if these were agreed before you started ? Some of the services are in different sized boxes.   Antivirus/ opswat is missing. It could probably benefit from an indication of the boundaries. Some of the arrows seem to go no where . There is what looks like a service called 'handle form type' , which is a function not a service. Possibly benefit from some notes ?

**Review by gavinleeedwards — CHANGES_REQUESTED** [review]
- sdx-sequence service is missing from the diagram
- rm-sdx-gateway and minifi aren't SDX services, so can it be made clear what systems they relate to (i.e. rm-sdx-gateway is a RASRM service)
- Can you show the boundaries of what is included in SDX and what belongs to other systems (eQ, RASRM, Data capture)
- rm-sdx-gateway and minifi have arrows going nowhere
- can it be made clear that we only send the encryted json to DAP.  Also, when we send to DAP, I wasn't aware that they accessed our postgres db.
- It would be useful to show that the seft-consumer service makes an external call to OPSWAT for AV checking
- What is 'Handle form type'?
- It'd be handy to show the quarantine queues for validate and seft-consumer
- Could we show the type of requests for each call (GET or POST)
- What's 'Service decrypt' at the bottom of the diagram
- 'FTP Server' isn't  service so it shouldn't be a box like the others

**Comment by insacuri** [comment]
I've got a few more comments about it.  If you've got any questions then @necrophonic or (hopefully) anyone else on the team can answer it.
I'd strongly advise that you fire up sdx-compose on your machine and put a survey though it using the console (http://localhost when you've got the service up and running).  If you turn down the logging to info (described in the README) then you can see the flow a survey takes though the system so you can compare it to your diagram.
Putting though a seft survey, an lms survey, the feedback survey and a regular one that doesn't go to DAP (I think I gave you the list) you can see the path it takes.
The SEFT survey can be any old excel file with a .xlsx extension.  You can't view it in console but you CAN see it in <whereever you have compose>/pure-ftp-structure/survey_ref.

And now for the comments:
 - The SEFT journey should be in it's own image file to simplify the diagram as there are a lot of boxes
 - sdx-receipt-rrm IS part of sdx.  It might be better to denote SDX reaching out to an external service with maybe a dashed line with an arrow at the end?
 - downstream only does 1 thing with transform-cs.  I'm fairly sure it's just a post.
 - transform-cs does a call to sdx-sequence in order to get the image numbers.  sdx-sequence I think interacts with the database directly to get the sequence number.
 - You're missing the arrow from downstream to the FTP.  This is the whole point of SDX so it's an important arrow to miss!
 - You're missing the entire DAP journey.  This should be a separate image on its own as you can describe the path it takes without having a bunch of superfluous boxes.
- The description at the top is wrong and probably not needed.  Feedback surveys only go as far as sdx-store (no receipt or downstream). DAP bound surveys get a message written to the DAP queue instead of downstream and receipting happens as normal.  The rest go downstream and get receipted.

**Review by insacuri — DISMISSED** [review]

**Review by gavinleeedwards — CHANGES_REQUESTED** [review]
- For the SEFT diagram, can it be made clear that OPSWAT isn't a microservice that's under the control of SDX.
- Same with the DAP diagram - can it be made clear that MINIFI, NIFI and Ark are not SDX services

**Review by gavinleeedwards — APPROVED** [review]

**Review by insacuri — APPROVED** [review]

**Pull request merged**
